#!/bin/sh
#
# SWUpdate Webserver REST/API 

case "$1" in
    start)
        echo "Starting SWUpdate Web Server..."
        /usr/bin/swupdate -w "--document-root /var/www/swupdate --port 10000" &
        ;;
    stop)
        echo "Stopping SWUpdate Web Server..."
        pkill -f "swupdate -w"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
