#!/bin/sh
#
# OTA Agent (responds to discovery, and reboots to otafs for updates)
case "$1" in
    start)
        echo "Starting OTA Agent..."
        /usr/local/bin/ota-agent &
        ;;
    stop)
        echo "Stopping OTA Agent..."
        killall swupdate
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0